# Identificador único do projeto no SonarQube
sonar.projectKey=lwsa-gabriel-cardoso_fc2-sonarcloud
sonar.organization=lwsa-gabriel-cardoso

# Diretório onde estão os arquivos de código-fonte a serem analisados
# "." significa o diretório atual
sonar.sources=.

# Arquivos que devem ser EXCLUÍDOS da análise de código-fonte
# Aqui exclui todos os arquivos de teste (*_test.go)
sonar.exclusions=**/*_test.go

# Diretório onde estão os arquivos de TESTE
# "." significa o diretório atual
sonar.tests=.

# Arquivos que devem ser INCLUÍDOS como testes
# Inclui todos os arquivos que terminam com _test.go
sonar.test.inclusions=**/*_test.go


# Caminho para o arquivo de cobertura de código gerado pelo Go
# Este arquivo é criado com: go test -coverprofile=coverage.out
sonar.go.coverage.reportPaths=coverage.out






# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=fc2-sonarcloud
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8